## Intro to Deep Learning: Lecture 2 (demo notebook)

Refer to the [slides](https://samvangool.net/iap/iap-cours2.pdf) for more context.

### Softmax example

In [1]:
import numpy as np

In [2]:
o = np.array([1.,0,-4])
o

array([ 1.,  0., -4.])

In [3]:
np.exp(o)

array([2.71828183, 1.        , 0.01831564])

In [4]:
P = np.sum(np.exp(o))

In [5]:
np.exp(o) / P

array([0.72747516, 0.26762315, 0.00490169])

### The graph of softmax

We show what the first coordinate of softmax looks like when we have two classes.

In [6]:
import plotly.graph_objects as go

x = np.linspace(-10, 10, 101)
y = np.linspace(-10, 10, 101)
x, y = np.meshgrid(x,y)
os = np.array([x,y])

P = np.sum(np.exp(os),axis=0)
z = (np.exp(os) / P)[0] # first coordinate

In [7]:
fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
fig.update_layout(title='Softmax', autosize=False, width=700, height=700,
                  scene=dict(xaxis_title='o1', yaxis_title='o2', zaxis_title='p1'))
fig.show()

In [8]:
import plotly.express as px

fig_heatmap = px.imshow(z, x=x[0], y=y[:,0], labels={'x': 'o1', 'y': 'o2', 'color': 'p1'})
fig_heatmap.update_layout(title='Softmax Heatmap', autosize=False, width=700, height=700)
fig_heatmap.show()

### Numeric instability

In [9]:
a = np.array([.0001] * 10)
b = 0.999
0.999 + np.sum(a)

np.float64(1.0)

In [10]:
b_arr = np.array([b])
c = np.concat([b_arr,a])
np.sum(c)

np.float64(0.9999999999999999)

In [11]:
a = np.array([.0001] * 100)
np.prod(a)

np.float64(0.0)

In [12]:
# NOTE: for demo purposes we here use log10 instead of log just to get readable numbers, 
# in practice always use log
loga = np.log10(a) 
loga

array([-4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4., -4.,
       -4., -4., -4., -4., -4., -4., -4., -4., -4.])

In [13]:
np.sum(loga)

np.float64(-400.0)

$\log \prod_{i=1}^I a_i = \sum_{i=1}^I \log a_i$ ?

In [14]:
np.log10(np.prod(a))

/var/folders/yq/hb1v9b0j32xfc4pj_2nywm8r0000gn/T/ipykernel_78648/3382569109.py:1: RuntimeWarning:

divide by zero encountered in log10



np.float64(-inf)

In [15]:
np.sum(np.log10(a))

np.float64(-400.0)